function(find_toolchain)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        if (DEFINED ENV{VCPKG_ROOT})
            set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
        else()
            if(WIN32)
                set(root_dir "C:")
            else()
                set(root_dir "$ENV{HOME}")
            endif()
            file(GLOB VCPKG_SEARCH_PATH ${root_dir}/*/vcpkg)
            Message(STATUS "VCPKG_SEARCH_PATH=${VCPKG_SEARCH_PATH}")
            unset(vcpkg_dir CACHE)
            find_path(vcpkg_dir .vcpkg-root PATHS ${VCPKG_SEARCH_PATH})
            set(CMAKE_TOOLCHAIN_FILE "${vcpkg_dir}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
        endif()
    endif()
    Message(STATUS "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}. set it in env or we will try to find it")
endfunction()